/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agrur;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sio
 */
public class ConsulterCommandeProducteur extends javax.swing.JFrame {

    private PersistanceSQL bdd;
    private Connection connect;
    String log;

    /**
     * Creates new form ConsulterCommandeProducteur
     */
    public ConsulterCommandeProducteur(String login) {
        initComponents();
        log = login;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consulter = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fermer = new javax.swing.JMenu();
        fichier_retour = new javax.swing.JMenuItem();
        fichier_deco = new javax.swing.JMenuItem();
        fichier_fermer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        consulter.setText("Consulter");
        consulter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulterActionPerformed(evt);
            }
        });

        fermer.setText("Fichier");

        fichier_retour.setText("Retour à l'accueil");
        fichier_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fichier_retourActionPerformed(evt);
            }
        });
        fermer.add(fichier_retour);

        fichier_deco.setText("Deconnexion");
        fichier_deco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fichier_decoActionPerformed(evt);
            }
        });
        fermer.add(fichier_deco);

        fichier_fermer.setText("Fermer");
        fichier_fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fichier_fermerActionPerformed(evt);
            }
        });
        fermer.add(fichier_fermer);

        jMenuBar1.add(fermer);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(consulter)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(consulter)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fichier_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fichier_retourActionPerformed
        AccueilProd accueil = new AccueilProd(log);
        accueil.setTitle("Acceuil");
        accueil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_fichier_retourActionPerformed

    private void fichier_decoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fichier_decoActionPerformed
        Connexion fen = new Connexion();
        fen.setTitle("Connexion");
        fen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_fichier_decoActionPerformed

    private void fichier_fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fichier_fermerActionPerformed
        this.dispose();
    }//GEN-LAST:event_fichier_fermerActionPerformed

    private void consulterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulterActionPerformed
        try {
            bdd = new PersistanceSQL("root", "", "jdbc:mysql://localhost/gestcommande", "org.gjt.mm.mysql.Driver");
            Class.forName("org.gjt.mm.mysql.Driver");
            connect = DriverManager.getConnection("jdbc:mysql://localhost/gestcommande", "root", "");
            
            String req = "SELECT id AS nb FROM commande WHERE idDistributeur=?";
            PreparedStatement exe = connect.prepareStatement(req);
            exe.setString(1, log);
            ResultSet r = exe.executeQuery();
            int nb = 0;
            if (r.next()) {
                nb = r.getInt("nb");
            }
            
            /*String libRequete = "SELECT prixHT,conditionnement,quantite,dateConditionnement,dateEnvoi,idProduit FROM commande WHERE idDistributeur=?";
            PreparedStatement reqExe = connect.prepareStatement(libRequete);
            reqExe.setString(1, log);
            ResultSet res = reqExe.executeQuery();
            if (res.next()) {
                if (res.getDate(5) == null) {
                    int idProd = res.getInt(6);
                    String libRequete2 = "SELECT varieteProduit,typeProduit,calibreProduit FROM produit WHERE idProduit=?";
                    PreparedStatement reqExe2 = connect.prepareStatement(libRequete2);
                    reqExe2.setInt(1, idProd);
                    ResultSet res2 = reqExe2.executeQuery();
                    if (res2.next()) {
                        String variete = res2.getString(1);
                        String type = res2.getString(2);
                        int calibre = res2.getInt(3);
                        Produit produit = new Produit(variete, type, calibre);

                        String libRequete3 = "SELECT nomDistributeur FROM distributeur WHERE idDistributeur=?";
                        PreparedStatement reqExe3 = connect.prepareStatement(libRequete3);
                        reqExe3.setString(1, log);
                        ResultSet res3 = reqExe3.executeQuery();
                        if (res3.next()) {
                            String nom = res3.getString(1);
                            Distributeur distributeur = new Distributeur(log, nom);
                            double prixHT = res.getDouble(1);
                            String conditionnement = res.getString(2);
                            int quantite = res.getInt(3);
                            String dateConditionnement = res.getDate(4) + "";
                            
                            Commande commande = new Commande(idCommande, produit, prixHT, conditionnement, quantite, dateConditionnement);
                            String chaine = commande.XMLCommande();
                            System.out.println(chaine);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "La commande que vous demandez est achevée.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Il n'existe aucune commande correspondant à cet identifiant.");
            }*/
        } catch (IOException ex) {
            Logger.getLogger(Connexion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Connexion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Connexion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_consulterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsulterCommandeProducteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsulterCommandeProducteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsulterCommandeProducteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsulterCommandeProducteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consulter;
    private javax.swing.JMenu fermer;
    private javax.swing.JMenuItem fichier_deco;
    private javax.swing.JMenuItem fichier_fermer;
    private javax.swing.JMenuItem fichier_retour;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
