/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agrur;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.transform.TransformerException;

/**
 *
 * @author Thibault
 */
public class ConsulterCommandes extends javax.swing.JFrame {

    private PersistanceSQL bdd;
    private Connection connect;
    private BufferedWriter fw;
    
    /**
     * Creates new form ConsulterCommandes
     */
    public ConsulterCommandes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idProd = new javax.swing.JTextField();
        consulter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Identifiant du producteur :");

        idProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProdActionPerformed(evt);
            }
        });

        consulter.setText("Consulter les commandes");
        consulter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idProd, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(consulter)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(consulter)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProdActionPerformed

    private void consulterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulterActionPerformed
        try {
            bdd = new PersistanceSQL("root", "", "jdbc:mysql://localhost/gestcommande", "org.gjt.mm.mysql.Driver");
            Class.forName("org.gjt.mm.mysql.Driver");
            connect = DriverManager.getConnection("jdbc:mysql://localhost/gestcommande", "root", "");

            String log = idProd.getText();
            String libRequete3 = "SELECT nomDistributeur FROM distributeur WHERE idDistributeur=?";
            PreparedStatement reqExe3 = connect.prepareStatement(libRequete3);
            reqExe3.setString(1, log);
            ResultSet res3 = reqExe3.executeQuery();
            if (res3.next()) {
                String nom = res3.getString(1);
                Distributeur distributeur = new Distributeur(log, nom);
                
                String libRequete = "SELECT id,prixHT,conditionnement,quantite,dateConditionnement,dateEnvoi,idProduit FROM commande WHERE idDistributeur=?";
                PreparedStatement reqExe = connect.prepareStatement(libRequete);
                reqExe.setString(1, log);
                ResultSet res = reqExe.executeQuery();
                if (res.next()) {
                    do{
                        int id = res.getInt(1);
                        if (res.getDate(6) == null) {
                            int idProd = res.getInt(7);
                            String libRequete2 = "SELECT varieteProduit,typeProduit,calibreProduit FROM produit WHERE idProduit=?";
                            PreparedStatement reqExe2 = connect.prepareStatement(libRequete2);
                            reqExe2.setInt(1, idProd);
                            ResultSet res2 = reqExe2.executeQuery();
                            if (res2.next()) {
                                String variete = res2.getString(1);
                                String type = res2.getString(2);
                                int calibre = res2.getInt(3);
                                Produit produit = new Produit(variete, type, calibre);

                                double prixHT = res.getDouble(2);
                                String conditionnement = res.getString(3);
                                int quantite = res.getInt(4);
                                String dateConditionnement = res.getDate(5) + "";

                                Commande commande = new Commande(id, produit, prixHT, conditionnement, quantite, dateConditionnement);

                                distributeur.addCommande(commande);
                            }
                        }
                        else{
                            
                        }
                    }while(res.next());
                    GestionCommandes gc = new GestionCommandes(bdd);
                    String chaine = gc.XmlNonLivrees(distributeur);
                    
                    File fichier = new File("Commandes en cours du producteur " + log +".txt");
                    fw = new BufferedWriter(new FileWriter(fichier));
                    fw.write(chaine.replace("\n","\r\n"));
                    fw.close();
                    //System.out.println(chaine);
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(Connexion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Connexion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Connexion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(ConsulterCommandeProducteur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_consulterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsulterCommandes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsulterCommandes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsulterCommandes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsulterCommandes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consulter;
    private javax.swing.JTextField idProd;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
